### PR TITLE
Remove boost dependency on mutex, thread and shared_ptr

### PR DESCRIPTION
**Pull request by guchaojie**
Replace boost::mutex::scoped_lock with std::unique_lock<std::mutex>
Replace boost::mutex with std::mutex
Replace boost::thread with std::thread
Replace boost::shared_ptr with std::shared_ptr

### CODE REVIEW

**Comment by bponsler** [comment]
Fantastic, thanks for your help

**Comment by guchaojie** [comment]
@bponsler  I found  boost::shared_array<char> data  , we can replace it with char *data to do that,
and userLatency = boost::lexical_cast<double>(strLatency);  we can replace it with atof function to do that.
I think these two ways seems too C coding style to replace boost library, do u think this is necessary?

**Comment by bponsler** [comment]
Good questions. I don't think it's necessary at this point. From reading the migration guide, it says:

> Much of the functionality previously provided by Boost has been integrated into C++11. As such we would like to take advantage of the new core features and avoid the dependency on boost where possible.

I think the key word there is "where possible". I think it makes complete sense to switch to the std equivalent when there is an exact match, but may not be worth the effort to make changes purely to remove boost. If, in the future, these uses of boost are preventing the port from being used/accepted then we can cross that bridge at that time. Thoughts?

**Comment by guchaojie** [comment]
@bponsler I think so,  we are at the same page.

**Pull request merged**
